version: "3.8"

services:
  api:
    build: .
    command: node src/server.js
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: node src/workers/runWorker.js
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eventbridge
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redisdata:
  pgdata:
